### PR TITLE
Added missed parenthesis

### PR DESCRIPTION
**Pull request by sergeyklay**

### CODE REVIEW

**Comment by sergeyklay** [comment]
@cheshirekow Here is my gpg signing key: 
image

---

This key is present on keyservers:
- [https://keyserver.ubuntu.com/pks/lookup?search=**`0xC6AF1016BBDEA800`**&fingerprint=on&op=get](https://keyserver.ubuntu.com/pks/lookup?search=0xC6AF1016BBDEA800&fingerprint=on&op=get)
- [https://pgp.key-server.io/pks/lookup?search=**`0xC6AF1016BBDEA800`**&fingerprint=on&op=get](https://pgp.key-server.io/pks/lookup?search=0xC6AF1016BBDEA800&fingerprint=on&op=get)
- [http://pgp.cyberbits.eu/pks/lookup?search=**`0xC6AF1016BBDEA800`**&op=get](http://pgp.cyberbits.eu/pks/lookup?search=0xC6AF1016BBDEA800&op=get)

---

```
$ gpg --keyserver hkp://pgpkeys.eu --search-keys 0xC6AF1016BBDEA800
gpg: data source: http://pgpkeys.eu:11371
(1)	Serghei Iakovlev <sadhooklay@gmail.com>
	  4096 bit RSA key 0x1E0B5331219BEA88, created: 2019-05-13, expires: 2020-05-12
Keys 1-1 of 1 for "0xC6AF1016BBDEA800".  Enter number(s), N)ext, or Q)uit >
```

But Travis still says:
> AssertionError: Could not find signer `C6AF1016BBDEA800` in signature database

**Comment by sergeyklay** [comment]
@cheshirekow Could you please advice me the right direction and tell me what exactly I should do to start contributing, as well as whether I should use [individual_ca.txt](https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/contrib/individual_ca.txt) and [signature_db.json](https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/contrib/signature_db.json) files?  

Related: https://github.com/cheshirekow/cmake_format/issues/150

**Comment by cheshirekow** [comment]
> AssertionError: Could not find signer `C6AF1016BBDEA800` in signature database

The signature database this test is referring to is `signature_db.json`. But don't sweat it, I've pulled your typo fixes in upstream and I'll include them in the next push.

**Comment by sergeyklay** [comment]
Closed in favor of https://github.com/cheshirekow/cmake_format/pull/151

**Pull request closed without merging**
